Repository cooperative-computing-lab/cctools, pull requests merged in 2020-07, with the labels that each got.

#2300 Adds ubuntu image to travis testing
  .travis.yml
  configure
  packaging/scripts/generate-images
  work_queue/test/TR_work_queue_valgrind.sh
Labels: enhancement, infrastructure

#2343 JX Iterative Parsing
  dttools/src/jx_parse.c
  dttools/src/jx_test.c
Labels: JX, bug

#2348 JX Prefix and Postfix Operators
  dttools/src/jx_parse.c
  dttools/test/jx.expected
  dttools/test/jx.input
Labels: JX, bug

#2342 Refactor JX functions
  dttools/src/jx_eval.c
  dttools/src/jx_function.c
  dttools/src/jx_function.h
  dttools/src/jx_parse.c
  dttools/src/jx_test.c
  dttools/test/jx.expected
  dttools/test/jx.input
Labels: JX, infrastructure
