Repository cooperative-computing-lab/cctools, pull requests merged in 2020-04, with the labels that each got.

#2266 Return the number of physical CPUs from load_average_get_cpus()
  doc/man/.gitignore
  dttools/src/load_average.c
  makeflow/test/TR_makeflow_alloc_output.sh
  resource_monitor/src/.gitignore
  work_queue/src/.gitignore
Labels: bug, infrastructure

#2253 Python interface for wq factory
  work_queue/src/bindings/python3/work_queue.binding.py
Labels: Work Queue

#2254 Python Packaging Cleanup
  python_packaging/README.md
  python_packaging/list_functions
  python_packaging/python_package_analyze
  python_packaging/python_package_create
  python_packaging/python_package_run
Labels: enhancement, infrastructure
