Repository cooperative-computing-lab/cctools, pull requests merged in 2022-06, with the labels that each got.

#2878 Misc OSX 12.0.1 Build Fixes
  chirp/src/Makefile
  chirp/src/chirp_benchmark.c
  chirp/src/chirp_multi.c
Labels: infrastructure

#2890 Doc: Add Logos to Manuals
  doc/manuals/chirp/index.md
  doc/manuals/index.md
  doc/manuals/jx/index.md
  doc/manuals/logos/cctools-logo.png
  doc/manuals/logos/chirp-logo.png
  doc/manuals/logos/jx-logo.png
  doc/manuals/logos/makeflow-logo.png
  doc/manuals/logos/parrot-logo.png
  doc/manuals/logos/resource-monitor-logo.png
  doc/manuals/logos/workqueue-logo.png
  doc/manuals/makeflow/index.md
  doc/manuals/parrot/index.md
  doc/manuals/resource_monitor/index.md
  doc/manuals/work_queue/index.md
Labels: enhancement, documentation

#2891 JX: Added flags to enable/disable external function calls.
  doc/manuals/jx/reference.md
  dttools/src/jx2json.c
  dttools/src/jx_eval.c
  dttools/src/jx_eval.h
  dttools/src/jx_function.c
  dttools/src/jx_repl.c
  dttools/src/jx_test.c
  makeflow/src/makeflow.c
Labels: enhancement, JX

#2897 Include cache information in the transfer transaction
  work_queue/src/work_queue.c
Labels: Work Queue
